### ISSUE TITLE
Problem with importing module "notebooks"

### ISSUE THREAD

**Issue by miqbal23** [Azure/MachineLearningSamples-DocumentCollectionAnalysis#7]
Hi,
I tried to use the notebooks outside Azure ML Workbench. When I tried to run the code in notebook **2_Phrase_Learning**, I got error in function `ComputeNgramStats` said that there's no module `notebooks`

I tried to change it to `notebook` (guessing that you might mistyped it), but the `winprocess` didn't exist.

How do I solve this problem

**Comment by kehuangms** [comment]
The module 'notebooks' is the folder name that contains all the example notebooks and a 'winprocess.py' file. It is NOT recommended to run those notebooks outside of Azure ML Workbench, otherwise you will encounter a few file reference error. If you really want to run it outside of AML Workbench, you will need to copy over the 'winprocess.py' file as well (only need it if you are using Windows system), and change the code 'from notebooks import winprocess' to 'import winprocess'.
